[default]
host = DC-Core

[WinEventLog://Security]
disabled = 0
start_from = oldest
interval = 2
renderXml = true
index = windows

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
start_from = oldest
interval = 2
renderXml = true
index = windows
